---
title: 
   <center><h2> Google Play Store Analytics with R </h2></center>
subtitle: 
   <center><h3> Midterm Report </h3> </center>
author: 
  <center><h5> Group3- Sumadhuri Damerla,Shaoor Jan,Ashjan Khan </h5> </center>
output: 
   html_document: 
    theme: cosmo
    highlight: monochrome
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 4
    fig_caption: true
    number_sections: true
    df_print: paged
---
```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=10, fig.height=8,echo=FALSE, warning=FALSE, message=FALSE)
```

# Introduction to the dataset  
## Data source
The data source used for this analysis is the *2018 google play store*(https://www.kaggle.com/lava18/google-play-store-apps) collected from Kaggle.

## Description of the dataset
The dataset is a collection of web-scraped data of 10,000 apps from Google Play Store. Google Play Store originally referred as the Android Market, is Google's official store and portal for Android apps, games and other content for Android-powered phone, tablet or Android TV device. As of May 2017, it has over two billion monthly active users, the largest installed base of any operating system, and as of January 2020, the Google Play Store features over 2.9 million apps.

The variables of the dataset are as follows:

1)	App (Name) – Name/Title of the application
2)	Category (App)- Category/Domain to which  the app belongs to
3)	Rating (App)- Overall user rating of the app
4)	Reviews (User)- Number of user reviews for the app 
5)	Size (App)- Space or memory that the app takes up 
6)	Installs (App)- Number of user downloads/installs 
7)	Type (Free/Paid)-Apps may be free or paid depending on the developer’s choice
8)	Price (App)-Price of the app if not free
9)	Content Rating -  Age group the app is based off at - Children / Mature 21+ / Adult
10)	Genres (Detailed Category)- An app can belong to multiple genres, For eg, a musical family game will belong to Music, Game, Family genres.
11)	Last Updated (App)- Date when the app was last updated on Play Store 
12)	Current Version (App)- Current version of the app available on Play Store  
13)	Android Version (Support) – minimum version of android it takes to have the app on the device


# Purpose of the project
The aim of our project is to find out if we can predict ratings of an app based on different variables and we intend to perform analysis to find out different factors that influence the success of an app. To gather insights from data that is valuable for android developer community. These analyses will help them build successful apps, by taking data backed decisions, and focusing on those aspects of applications that matters most.

We also aim to strengthen the concepts learned during the course by taking a hands-on approach.

# Intended audience of the project
We believe there's a diverse set of audience who might be interested in our project. As of Febraury 2020, 73.3% of the mobile operating system market share belongs to Android devices[]. Because of such a large market share it has a large, and growing, developer community. This project is primarily intended for this growing developer community. It will help them make data backed decisions before launching their application. Besides developers, it is also for hobbiests, tech journalists and Google Play Store users.  

# Data exploration using EDA



# Future work (models)  
## What are we trying to achieve (thesis/hypothesis)
The dataset we have contains information about 10000 apps dated till 2018. With the dataset, we plan on using Clustering Model, Forecast Model and Random Forest to perform predictive analysis. We want to answer the following hypothesis:  

1) Find similarities in apps that make it to the top of Play Store. Factors contribute to the success of applications.
2) Predict rating of apps based on other parameters such as number of reviews or the size of an app. 

To answer these questions, we will be exploring all the variables of this dataset. Try to find if there's any relationship between rating and other variables. We intend to find out which of these variables will play the most important role in predicting rating.
 

## Why is this important/interesting?
Recently, we took part in a competition called game-jam [12] where they must build a game based on a theme, while we successfully built the game, we thought of launching it at Google Play Store. Normally, there are many external factors influencing an applications success. We thought it would be interesting to see currents trends in the market and a detailed analysis of which factors influence rating, and which categories are highly installed, what are the most famous applications and do they have any trends in common like number of installs, number of reviews, size or android-version? 
These analyses will also help the developer community to build more successful apps targeting a specific audience.


## How are we going to test the hypothesis?
Since the dataset is dated till 2018.  We can test by comparing out pridictions with the latest data. 


## Any challenges that we might encounter
There is a lot of useful information that could have given us more insight into the Play Store market e.g. Demographic data could have offered insights into the rating and number of installs of apps, with respect to different regions,  different cultures and different trends popular to specific age groups. Also, it would have been interesting to see how different global trends affect the usage of the app, for instance, the current pandemic "covid-19" has called for quarantine across the globe and many people, markets and other companies are relying on smart phones and virtual connections, this will heavily increase the use of many applications, thus deviating from the general trend. 

# References

[1] [Dataset](https://www.kaggle.com/lava18/google-play-store-apps);  
[2] [R markdown](https://bookdown.org/yihui/rmarkdown/html-document.html#tabbed-sections) ;  
[3] [Stackoverflow](https://stackoverflow.com/questions/3993301/how-to-format-number-values-for-ggplot2-legend/15007117) ;  
[4] [GGally](https://ggobi.github.io/ggally/rd.html#ggpairs);  
[5] [Custom color pallete](https://drsimonj.svbtle.com/creating-corporate-colour-palettes-for-ggplot2);  
[6] [Tidying data](https://medium.com/coinmonks/dealing-with-missing-data-using-r-3ae428da2d17);  
[7] [Colors](https://hbr.org/2014/04/the-right-colors-make-data-easier-to-read);  
[8] [TidyVerse](https://www.tidyverse.org/);  
[9] [ggplot2](https://ggplot2.tidyverse.org/reference/);  
[10] [Google playstore Kernel by Danilodiogo](https://www.kaggle.com/danilodiogo/google-play-store-eda-plotting-with-highcharts/code#eda);  
[11] [market share]https://gs.statcounter.com/os-market-share/mobile/worldwide ;  
[12] [Global game jam]https://globalgamejam.org/ ;  
[13] [Play Store Statistics]https://www.statista.com/statistics/266210/number-of-available-applications-in-the-google-play-store/ ;  
